version: '3.9'

services:
  postgres:
    image: postgres:latest
    container_name: postgres_db
    restart: always
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin
      POSTGRES_DB: carBigData
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  minio:
    image: quay.io/minio/minio:latest
    container_name: minio
    restart: always
    environment:
      MINIO_ROOT_USER: minioadmin
      MINIO_ROOT_PASSWORD: minioadmin
    ports:
      - "9000:9000"
      - "9090:9090"
    volumes:
      - minio_data:/data
    entrypoint: >
      sh -c "mkdir -p /data/occurrences && 
             minio server /data --console-address ':9090'"

  app:
    build: .
    container_name: java_app
    restart: always
    depends_on:
      - postgres
      - minio
    environment:
      SERVER_PORT: 8080
      APP_DB_URL: jdbc:postgresql://postgres:5432/carBigData
      APP_DB_USERNAME: admin
      APP_DB_PASSWORD: admin
      API_SECURITY_TOKEN_SECRET: 12312312312
      MINIO_URL: http://minio:9000
      MINIO_ACCESS_KEY: minioadmin
      MINIO_SECRET_KEY: minioadmin
      MINIO_BUCKET_NAME: occurrences
      ENABLE_SWAGGER: true
    volumes:
      - ./target/teste-0.0.1-SNAPSHOT.jar:/app.jar
    entrypoint: [ "java", "-jar", "/app.jar" ]
    ports:
      - "8080:8080"

volumes:
  postgres_data:
  minio_data: